name: mikesten
favicon: null
layout_spectrum: 0
typography_spectrum: 0.82452
title: Quotes and other findings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9698100504465401
  lightness: 0.20496190222911537
  saturation: 0.874766418710351
  rhythmicContrast: 0.3724558858666569
purpose: []
